[2025-02-13T05:57:10.851+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-13T05:57:10.885+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_INETUM_ETL.clear_data_task manual__2025-02-13T05:56:39.893424+00:00 [queued]>
[2025-02-13T05:57:10.900+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_INETUM_ETL.clear_data_task manual__2025-02-13T05:56:39.893424+00:00 [queued]>
[2025-02-13T05:57:10.901+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-02-13T05:57:10.926+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): clear_data_task> on 2025-02-13 05:56:39.893424+00:00
[2025-02-13T05:57:10.939+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5357) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-13T05:57:10.944+0000] {standard_task_runner.py:63} INFO - Started process 5366 to run task
[2025-02-13T05:57:10.944+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DAG_INETUM_ETL', 'clear_data_task', 'manual__2025-02-13T05:56:39.893424+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmptru9k7x5']
[2025-02-13T05:57:10.947+0000] {standard_task_runner.py:91} INFO - Job 78: Subtask clear_data_task
[2025-02-13T05:57:11.036+0000] {task_command.py:426} INFO - Running <TaskInstance: DAG_INETUM_ETL.clear_data_task manual__2025-02-13T05:56:39.893424+00:00 [running]> on host 9a237c96c334
[2025-02-13T05:57:11.214+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Andres Urrea' AIRFLOW_CTX_DAG_ID='DAG_INETUM_ETL' AIRFLOW_CTX_TASK_ID='clear_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T05:56:39.893424+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T05:56:39.893424+00:00'
[2025-02-13T05:57:11.217+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-13T05:57:11.218+0000] {dag_etl.py:98} INFO - El archivo temporal /tmp/archivo.json eliminado correctamente.
[2025-02-13T05:57:11.219+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-02-13T05:57:11.220+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-13T05:57:11.237+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=DAG_INETUM_ETL, task_id=clear_data_task, execution_date=20250213T055639, start_date=20250213T055710, end_date=20250213T055711
[2025-02-13T05:57:11.281+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-13T05:57:11.334+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-13T05:57:11.337+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
