[2025-02-11T16:24:15.578+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-11T16:24:15.619+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_ETL_glue.upload_to_s3 manual__2025-02-11T16:24:01.789563+00:00 [queued]>
[2025-02-11T16:24:15.635+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_ETL_glue.upload_to_s3 manual__2025-02-11T16:24:01.789563+00:00 [queued]>
[2025-02-11T16:24:15.636+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-02-11T16:24:15.667+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2025-02-11 16:24:01.789563+00:00
[2025-02-11T16:24:15.689+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2213) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-11T16:24:15.693+0000] {standard_task_runner.py:63} INFO - Started process 2215 to run task
[2025-02-11T16:24:15.692+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DAG_ETL_glue', 'upload_to_s3', 'manual__2025-02-11T16:24:01.789563+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpcrfb37ui']
[2025-02-11T16:24:15.694+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask upload_to_s3
[2025-02-11T16:24:15.799+0000] {task_command.py:426} INFO - Running <TaskInstance: DAG_ETL_glue.upload_to_s3 manual__2025-02-11T16:24:01.789563+00:00 [running]> on host 9a237c96c334
[2025-02-11T16:24:15.991+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Andres Urrea' AIRFLOW_CTX_DAG_ID='DAG_ETL_glue' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T16:24:01.789563+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T16:24:01.789563+00:00'
[2025-02-11T16:24:15.994+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-11T16:24:16.014+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2025-02-11T16:24:16.017+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-02-11T16:24:17.934+0000] {logging_mixin.py:188} INFO - Archivo /tmp/archivo.json subido a S3 en s3://source-data-spacenews/carpeta/archivo.json
[2025-02-11T16:24:17.937+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-02-11T16:24:17.938+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-11T16:24:17.959+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=DAG_ETL_glue, task_id=upload_to_s3, execution_date=20250211T162401, start_date=20250211T162415, end_date=20250211T162417
[2025-02-11T16:24:18.000+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-11T16:24:18.036+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-11T16:24:18.039+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
