[2025-02-11T17:10:42.309+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-11T17:10:42.344+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_INETUM_ETL.clear_data_task manual__2025-02-11T17:10:18.392643+00:00 [queued]>
[2025-02-11T17:10:42.359+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_INETUM_ETL.clear_data_task manual__2025-02-11T17:10:18.392643+00:00 [queued]>
[2025-02-11T17:10:42.360+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-02-11T17:10:42.388+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): clear_data_task> on 2025-02-11 17:10:18.392643+00:00
[2025-02-11T17:10:42.399+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2822) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-11T17:10:42.403+0000] {standard_task_runner.py:63} INFO - Started process 2824 to run task
[2025-02-11T17:10:42.403+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DAG_INETUM_ETL', 'clear_data_task', 'manual__2025-02-11T17:10:18.392643+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmp9iq5z02k']
[2025-02-11T17:10:42.405+0000] {standard_task_runner.py:91} INFO - Job 29: Subtask clear_data_task
[2025-02-11T17:10:42.501+0000] {task_command.py:426} INFO - Running <TaskInstance: DAG_INETUM_ETL.clear_data_task manual__2025-02-11T17:10:18.392643+00:00 [running]> on host 9a237c96c334
[2025-02-11T17:10:42.669+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Andres Urrea' AIRFLOW_CTX_DAG_ID='DAG_INETUM_ETL' AIRFLOW_CTX_TASK_ID='clear_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T17:10:18.392643+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T17:10:18.392643+00:00'
[2025-02-11T17:10:42.671+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-11T17:10:42.673+0000] {dag_etl.py:97} INFO - El archivo temporal /tmp/archivo.json eliminado correctamente.
[2025-02-11T17:10:42.674+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-02-11T17:10:42.675+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-11T17:10:42.692+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=DAG_INETUM_ETL, task_id=clear_data_task, execution_date=20250211T171018, start_date=20250211T171042, end_date=20250211T171042
[2025-02-11T17:10:42.739+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-11T17:10:42.776+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-11T17:10:42.779+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
