[2025-02-13T04:36:10.061+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-13T04:36:10.092+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_INETUM_ETL.extract_data manual__2025-02-13T04:36:03.187433+00:00 [queued]>
[2025-02-13T04:36:10.107+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_INETUM_ETL.extract_data manual__2025-02-13T04:36:03.187433+00:00 [queued]>
[2025-02-13T04:36:10.108+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-02-13T04:36:10.134+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): extract_data> on 2025-02-13 04:36:03.187433+00:00
[2025-02-13T04:36:10.145+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4355) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-13T04:36:10.148+0000] {standard_task_runner.py:63} INFO - Started process 4364 to run task
[2025-02-13T04:36:10.149+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DAG_INETUM_ETL', 'extract_data', 'manual__2025-02-13T04:36:03.187433+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpsuc3107r']
[2025-02-13T04:36:10.152+0000] {standard_task_runner.py:91} INFO - Job 67: Subtask extract_data
[2025-02-13T04:36:10.238+0000] {task_command.py:426} INFO - Running <TaskInstance: DAG_INETUM_ETL.extract_data manual__2025-02-13T04:36:03.187433+00:00 [running]> on host 9a237c96c334
[2025-02-13T04:36:10.423+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Andres Urrea' AIRFLOW_CTX_DAG_ID='DAG_INETUM_ETL' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T04:36:03.187433+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T04:36:03.187433+00:00'
[2025-02-13T04:36:10.426+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-13T04:36:11.483+0000] {dag_etl.py:46} INFO - Proceso de extraccion de data realizado con exito
[2025-02-13T04:36:11.494+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-02-13T04:36:11.496+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-13T04:36:11.517+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=DAG_INETUM_ETL, task_id=extract_data, execution_date=20250213T043603, start_date=20250213T043610, end_date=20250213T043611
[2025-02-13T04:36:11.574+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-13T04:36:11.639+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-13T04:36:11.642+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
